let azmi;
console.log("uper")

// try and catch use for error handling if try blockc any erro then go catch block not crash server

try{
    console.log(azmi.length)
}catch(error){
    console.log(error)
}
console.log("lover")


